Add `touch-action`
ryboe/CSS3 pull request #156
Opened 2021-03-01 05:58 UTC by argyleink

![Screen Shot 2021-02-28 at 9 55 58 PM](https://user-images.githubusercontent.com/1134620/109457580-fc3ebc00-7a0f-11eb-9f31-233ef9dee41e.png)

2021-03-03 00:49 UTC, ryboe requested changes
Thank you! This looks great! 👏
 
I'm proposing one easy change and then I'll happily merge this.

2021-03-03 16:22 UTC, argyleink commented on CSS3.sublime-syntax
> +        - match: '\b(?:auto|none|pan-x|pan-left|pan-right|pan-y|pan-up|pan-down|pinch-zoom|manipulation){{b}}'
sounds good 👍🏻 
how's this?

```suggestion
        - match: '\b(?:auto|none|manipulation|pinch-zoom|pan-x|pan-y|pan-up|pan-left|pan-right|pan-down){{b}}'
```

2021-03-04 01:46 UTC, ryboe commented on CSS3.sublime-syntax
> +        - match: '\b(?:auto|none|pan-x|pan-left|pan-right|pan-y|pan-up|pan-down|pinch-zoom|manipulation){{b}}'
Thanks for reverse alphabetizing that pattern!

2021-03-04 01:47 UTC, ryboe approved these changes

2021-03-04 01:47 UTC, merged